// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBbq3-SQluUBFo9nEtQFDclark2vEZ_-Y',
    appId: '1:1421067407:web:999b6880691bffadb65cfa',
    messagingSenderId: '1421067407',
    projectId: 'flutter-web-view-1d712',
    authDomain: 'flutter-web-view-1d712.firebaseapp.com',
    storageBucket: 'flutter-web-view-1d712.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCj8fhXKOmEpjlR3LX48c4JwHnnsRyB1w',
    appId: '1:1421067407:android:3a73c1e04cf6a0fab65cfa',
    messagingSenderId: '1421067407',
    projectId: 'flutter-web-view-1d712',
    storageBucket: 'flutter-web-view-1d712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxLy6iWHjAw9fIjEZV8t6-QxCGiqdv1Q',
    appId: '1:1421067407:ios:7de7b6e1763062f3b65cfa',
    messagingSenderId: '1421067407',
    projectId: 'flutter-web-view-1d712',
    storageBucket: 'flutter-web-view-1d712.appspot.com',
    iosClientId: '1421067407-hlrsuskai6263575jkv3i2j61c6bq618.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxLy6iWHjAw9fIjEZV8t6-QxCGiqdv1Q',
    appId: '1:1421067407:ios:7de7b6e1763062f3b65cfa',
    messagingSenderId: '1421067407',
    projectId: 'flutter-web-view-1d712',
    storageBucket: 'flutter-web-view-1d712.appspot.com',
    iosClientId: '1421067407-hlrsuskai6263575jkv3i2j61c6bq618.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebview',
  );
}
